### ISSUE TITLE
[BR]  volumeMounts in deployment.yaml only work when auth.enabled is true

### ISSUE THREAD

**Issue by obazda20** [vicsufer/charts#3]
Description:
Hi,
I encountered an issue with the deployment.yaml Helm template. Currently, the .Values.deployment.volumeMounts section is nested inside the if .Values.auth.enabled block. As a result, the additional volumeMounts defined by the user are only applied when auth.enabled is set to true.

Current Code:
```yaml
{{- if .Values.auth.enabled }}
- name: secrets
  mountPath: /mosquitto/config/passwords.conf
  subPath: passwords.conf
  readOnly: true
- name: config
  mountPath: /mosquitto/config/acl.conf
  subPath: acl.conf
  readOnly: true
{{- with .Values.deployment.volumeMounts }}
    {{- toYaml . | nindent 12 }}
{{- end }}
{{- end }}
```

This causes user-defined volumeMounts to be ignored when auth.enabled: false.

Proposed Fix:
Move the .Values.deployment.volumeMounts block outside of the auth.enabled conditional to ensure it is always evaluated:

```yaml
{{- if .Values.auth.enabled }}
- name: secrets
  mountPath: /mosquitto/config/passwords.conf
  subPath: passwords.conf
  readOnly: true
- name: config
  mountPath: /mosquitto/config/acl.conf
  subPath: acl.conf
  readOnly: true
{{- end }}
{{- with .Values.deployment.volumeMounts }}
    {{- toYaml . | nindent 12 }}
{{- end }}
```

Impact:
This change ensures that custom volumeMounts work independently of the auth.enabled setting, providing more flexibility for users.

Thanks for your attention, and great work on this char
